# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import immutable_log_pb2 as immutable__log__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in immutable_log_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImmutableLogServiceStub(object):
    """Immutable Event Log Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Append = channel.unary_unary(
                '/immutablelog.ImmutableLogService/Append',
                request_serializer=immutable__log__pb2.AppendRequest.SerializeToString,
                response_deserializer=immutable__log__pb2.AppendResponse.FromString,
                _registered_method=True)
        self.Read = channel.unary_stream(
                '/immutablelog.ImmutableLogService/Read',
                request_serializer=immutable__log__pb2.ReadRequest.SerializeToString,
                response_deserializer=immutable__log__pb2.ReadResponse.FromString,
                _registered_method=True)
        self.Verify = channel.unary_unary(
                '/immutablelog.ImmutableLogService/Verify',
                request_serializer=immutable__log__pb2.VerifyRequest.SerializeToString,
                response_deserializer=immutable__log__pb2.VerifyResponse.FromString,
                _registered_method=True)
        self.ListPartitions = channel.unary_unary(
                '/immutablelog.ImmutableLogService/ListPartitions',
                request_serializer=immutable__log__pb2.ListPartitionsRequest.SerializeToString,
                response_deserializer=immutable__log__pb2.ListPartitionsResponse.FromString,
                _registered_method=True)
        self.GetLastEntry = channel.unary_unary(
                '/immutablelog.ImmutableLogService/GetLastEntry',
                request_serializer=immutable__log__pb2.GetLastEntryRequest.SerializeToString,
                response_deserializer=immutable__log__pb2.GetLastEntryResponse.FromString,
                _registered_method=True)
        self.Tail = channel.unary_stream(
                '/immutablelog.ImmutableLogService/Tail',
                request_serializer=immutable__log__pb2.TailRequest.SerializeToString,
                response_deserializer=immutable__log__pb2.TailResponse.FromString,
                _registered_method=True)


class ImmutableLogServiceServicer(object):
    """Immutable Event Log Service
    """

    def Append(self, request, context):
        """Append an entry to a partition
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Read entries from a partition
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Verify(self, request, context):
        """Verify integrity of a partition
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPartitions(self, request, context):
        """List all available partitions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLastEntry(self, request, context):
        """Get the last entry from a partition (useful for sync)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Tail(self, request, context):
        """Tail a partition (streaming, like tail -f)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImmutableLogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Append': grpc.unary_unary_rpc_method_handler(
                    servicer.Append,
                    request_deserializer=immutable__log__pb2.AppendRequest.FromString,
                    response_serializer=immutable__log__pb2.AppendResponse.SerializeToString,
            ),
            'Read': grpc.unary_stream_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=immutable__log__pb2.ReadRequest.FromString,
                    response_serializer=immutable__log__pb2.ReadResponse.SerializeToString,
            ),
            'Verify': grpc.unary_unary_rpc_method_handler(
                    servicer.Verify,
                    request_deserializer=immutable__log__pb2.VerifyRequest.FromString,
                    response_serializer=immutable__log__pb2.VerifyResponse.SerializeToString,
            ),
            'ListPartitions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPartitions,
                    request_deserializer=immutable__log__pb2.ListPartitionsRequest.FromString,
                    response_serializer=immutable__log__pb2.ListPartitionsResponse.SerializeToString,
            ),
            'GetLastEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLastEntry,
                    request_deserializer=immutable__log__pb2.GetLastEntryRequest.FromString,
                    response_serializer=immutable__log__pb2.GetLastEntryResponse.SerializeToString,
            ),
            'Tail': grpc.unary_stream_rpc_method_handler(
                    servicer.Tail,
                    request_deserializer=immutable__log__pb2.TailRequest.FromString,
                    response_serializer=immutable__log__pb2.TailResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'immutablelog.ImmutableLogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('immutablelog.ImmutableLogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImmutableLogService(object):
    """Immutable Event Log Service
    """

    @staticmethod
    def Append(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/immutablelog.ImmutableLogService/Append',
            immutable__log__pb2.AppendRequest.SerializeToString,
            immutable__log__pb2.AppendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/immutablelog.ImmutableLogService/Read',
            immutable__log__pb2.ReadRequest.SerializeToString,
            immutable__log__pb2.ReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Verify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/immutablelog.ImmutableLogService/Verify',
            immutable__log__pb2.VerifyRequest.SerializeToString,
            immutable__log__pb2.VerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPartitions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/immutablelog.ImmutableLogService/ListPartitions',
            immutable__log__pb2.ListPartitionsRequest.SerializeToString,
            immutable__log__pb2.ListPartitionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLastEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/immutablelog.ImmutableLogService/GetLastEntry',
            immutable__log__pb2.GetLastEntryRequest.SerializeToString,
            immutable__log__pb2.GetLastEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Tail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/immutablelog.ImmutableLogService/Tail',
            immutable__log__pb2.TailRequest.SerializeToString,
            immutable__log__pb2.TailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
